### ISSUE TITLE
the first answer is the init answer

### ISSUE THREAD

**Issue by Kaidanov** [nathalie1226/minecraft#1]
Just choose the first picture and submit.
![image](https://cloud.githubusercontent.com/assets/164266/16837730/be584e8c-49cd-11e6-9df8-a03cfcdf44da.png)

**Comment by nathalie1226** [comment]
i know i just changed the init a little so that it is not

**Comment by nathalie1226** [comment]
and you can also try to achieve the second one 
i had fun playing it i even realized there was a bug that i corrected :-)
