### ISSUE TITLE
Duplicated jQuery

### ISSUE THREAD

**Issue by Kaidanov** [nathalie1226/minecraft#3]
$('#first').height(350);
$('#first').width(350);

$('#second').height(350);
$('#second').width(350);

$('.box');

 $('#treasure')   etc.

**Comment by nathalie1226** [comment]
i tried to chain them it just did not work i do not know why

**Comment by Kaidanov** [comment]
$('#treasure')  still used over and over. each time you are choosing it you are traversing through the DOM. 
if needed set a variable and use it. 
You can see this problem by yellow color stating the issues you have 
![image](https://cloud.githubusercontent.com/assets/164266/16857037/317849dc-4a26-11e6-96d6-35b17cd86942.png)
