### ISSUE TITLE
jQuery issues

### ISSUE THREAD

**Issue by Kaidanov** [nathalie1226/minecraft#4]
tileClicked.addClass(saved).removeClass('sky');
can use attr

document.getElementById ? why ? 

 if (!foundProblem) {
        $('#message').text('congratulations '+$("#playerName").val()+'!!! you are the best!!!');
        $('#lightbox').show();
    } else {
        $('#message').text('sorry you lost');
        $('#lightbox').show();
    }

if $('#lightbox').show(); is always activated why is it in if else ?

in render border minimize removeclasses to one row and one function. you can

**Comment by Kaidanov** [comment]
var bigBox = $("<div/>");
    bigBox.addClass("row");
    $('body').append(bigBox); 

can be done in one row

**Comment by nathalie1226** [comment]
done
there is an if else to change the content of the light box
