### ISSUE TITLE
Duplicate jQuery selector

### ISSUE THREAD

**Issue by Kaidanov** [nathalie1226/minecraft#5]
$('#treasure') still used over and over. each time you are choosing it you are traversing through the DOM. 
if needed set a variable and use it. 
You can see this problem by yellow color stating the issues you have 
![image](https://cloud.githubusercontent.com/assets/164266/16857067/52b670c4-4a26-11e6-97a7-5cbeb00a7442.png)

**Comment by Kaidanov** [comment]
minecraft.tiles = $('.box');
and then 
  $('.box').eq(i \* 20 + j).data("i", i).data("j", j) 

why aren't you using  minecraft.tiles ? 
You have it in variable already.

**Comment by nathalie1226** [comment]
i do not understand the problem with treasure you mean like create  var called 
var t=$('treasure')
??

**Comment by nathalie1226** [comment]
second part done
