### ISSUE TITLE
Multiple remove classes - is there any class left? - if not just remove all in one function and one row

### ISSUE THREAD

**Issue by Kaidanov** [nathalie1226/minecraft#7]
in render border minimize removeclasses to one row and one function. you can

   minecraft.tiles

```
    .removeClass("tree")
    .removeClass("leaf")
    .removeClass("dirt")
    .removeClass("grass")
    .removeClass("rock");
```

do it in one row

**Comment by nathalie1226** [comment]
i find it clearer for me like this is this bad practice?
because i even found my bug thanks to that structure....
